version: '2'
services:
    dalili-app:
        image: dalili
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dalili-postgresql:5432/dalili
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dalili-postgresql:
        extends:
            file: postgresql.yml
            service: dalili-postgresql
